//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XMSApi_Test.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_XMSAPI_TEST_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_PLAY                 129
#define IDD_DIALOG_CONTROLPLAY          130
#define IDD_DIALOG_RECORD               131
#define IDD_DIALOG_CONTROLRECORD        132
#define IDD_DIALOG_CONF                 134
#define IDD_DIALOG_PARAM_VOICE          135
#define IDD_DIALOG_BuildPlayIndex       136
#define IDD_DIALOG1                     137
#define IDD_DIALOG_PARAM_CAS            138
#define IDD_DIALOG_ANATRUNK             139
#define IDD_DIALOG_ANAUSER              140
#define IDD_DIALOG_RECCSP               141
#define IDD_DIALOG_PLAYCSP              142
#define IDD_DIALOG_PARAM_VOIP           143
#define IDD_DIALOG_PARAM_FSK            144
#define IDD_DIALOG_PARAM_Flash          145
#define IDD_DIALOG_GTD                  146
#define IDD_DIALOG_GTDSET               148
#define IDD_DIALOG_PARAM_ATRUNKFLASH    149
#define IDD_DIALOG_PARAM_3GFaxTone      150
#define IDD_DIALOG_PARAM_FAXHEADER      151
#define IDC_LIST_DEVICE_INFO            1000
#define IDC_BUTTON_OpenDevice           1001
#define IDC_EDIT_NOW_OPEN_DEVICE        1002
#define IDC_LIST_MSG                    1004
#define IDC_EDIT_SERVER_IPADDR          1005
#define IDC_EDIT_SERVER_IPPORT          1006
#define IDC_BUTTON_Exchange             1007
#define IDC_EDIT_DEVICE1                1008
#define IDC_EDIT_DEVICE2                1009
#define IDC_EDIT_DEVICE3                1010
#define IDC_BUTTON_CloseDevice          1011
#define IDC_BUTTON_ResetDevice          1012
#define IDC_BUTTON_GetDeviceList        1013
#define IDC_BUTTON_GetDeviceState       1014
#define IDC_BUTTON_SetDeviceGroup       1015
#define IDC_BUTTON_MakeCallOut          1016
#define IDC_EDIT_CALLINGNUM             1017
#define IDC_EDIT_CALLEDNUM              1018
#define IDC_BUTTON_SetParam             1019
#define IDC_BUTTON_GetParam             1020
#define IDC_BUTTON_AlertCall            1021
#define IDC_BUTTON_AnswerCallIn         1022
#define IDC_BUTTON_LinkDevice           1023
#define IDC_BUTTON_UnlinkDevice         1024
#define IDC_BUTTON_ClearCall            1025
#define IDC_BUTTON_JoinConf             1026
#define IDC_BUTTON_LeaveFromConf        1027
#define IDC_BUTTON_ClearConf            1028
#define IDC_BUTTON_Play                 1029
#define IDC_BUTTON_My_StopPlay          1030
#define IDC_BUTTON_Record               1031
#define IDC_BUTTON_My_StopRecord        1032
#define IDC_BUTTON_SendFax              1033
#define IDC_BUTTON_StopSendFax          1034
#define IDC_BUTTON_ReceiveFax           1035
#define IDC_BUTTON_StopReceiveFax       1036
#define IDC_BUTTON_SendIOData           1037
#define IDC_BUTTON_ControlPlay          1038
#define IDC_BUTTON_ControlRecord        1039
#define IDC_EDIT_SENDFAX                1040
#define IDC_EDIT_RECEIVEFAX             1041
#define IDC_COMBO_DEVICE                1042
#define IDC_LIST_MSG_HIDDEN             1043
#define IDC_COMBO_MSG                   1044
#define IDC_EDIT_PLAY                   1045
#define IDC_EDIT1_RECORD                1046
#define IDC_BUTTON_SelectSendFaxFile    1047
#define IDC_BUTTON_SelectReceiveFaxFile 1048
#define IDC_BUTTON_SelectPlayFile       1049
#define IDC_BUTTON_SelectRecordFile     1050
#define IDC_LIST_DEVICE_OPENED          1051
#define IDC_BUTTON_PlayDetail           1052
#define IDC_CHECK_AutoScroll            1053
#define IDC_EDIT_MsgDetail              1054
#define IDC_EDIT_Play_u32TaskID         1055
#define IDC_BUTTON_RecordDetail         1055
#define IDC_BUTTON_InitPlayIndex        1056
#define IDC_RADIO_PLAY_TYPE_FILE        1057
#define IDC_BUTTON_BuildPlayIndex       1057
#define IDC_RADIO_PLAY_TYPE_INDEX       1058
#define IDC_BUTTON_SelectBuildIndex     1058
#define IDC_BUTTON_SelectRecordFile2    1058
#define IDC_EDIT_Play_u32MaxSize        1059
#define IDC_BUTTON_SendFaxT38           1059
#define IDC_EDIT_Play_u32MaxTime        1060
#define IDC_BUTTON_StopSendFaxT38       1060
#define IDC_EDIT_Play_u32StopCode       1061
#define IDC_BUTTON_ReceiveFaxT38        1061
#define IDC_RADIO_SRC_8K                1062
#define IDC_BUTTON_StopReceiveFaxT38    1062
#define IDC_RADIO_SRC_6K                1063
#define IDC_BUTTON_GetBoardInfo         1063
#define IDC_RADIO_SRC_GTG               1064
#define IDC_RADIO_SRC_FSK               1065
#define IDC_RADIO_SRC_FAX               1066
#define IDC_RADIO_Alaw_type             1067
#define IDC_RADIO_Ulaw_type             1068
#define IDC_RADIO_Vox_type              1069
#define IDC_RADIO_Linear_8bit           1070
#define IDC_RADIO_Normal_Stop           1071
#define IDC_RADIO_Single_Code           1072
#define IDC_RADIO_Any_Code              1073
#define IDC_EDIT_Play_u16FileOffset     1074
#define IDC_RADIO_Linear_16bit          1074
#define IDC_EDIT_Play_u16PlayIndex      1075
#define IDC_RADIO_PLAY_FILE_NORMAL      1076
#define IDC_RADIO_PLAY_FILE             1076
#define IDC_RADIO_Play_Linear_16bit     1076
#define IDC_RADIO_PLAY_FILE_QUEUE       1077
#define IDC_RADIO_PLAY_TYPE_FILE_QUEUE  1077
#define IDC_RADIO_PLAY_TONE             1078
#define IDC_RADIO_GEN_DTMF              1079
#define IDC_RADIO_GEN_MR2F              1080
#define IDC_RADIO_GEN_MR2B              1081
#define IDC_RADIO_GEN_GTG               1082
#define IDC_EDIT_Play_u16GtgCodeLen     1083
#define IDC_EDIT_u16StepSize            1083
#define IDC_EDIT_Gtg_s8PlayContent      1084
#define IDC_EDIT2                       1084
#define IDC_EDIT_Play_s8PlayContent     1085
#define IDC_EDIT3                       1085
#define IDC_EDIT_Play_DevcieID          1086
#define IDC_EDIT_FREQ2_COEF             1086
#define IDC_RADIO_PLAY_TYPE_INDEX_QUEUE 1087
#define IDC_EDIT_FREQ3_COEF             1087
#define IDC_BUTTON_Stop                 1092
#define IDC_BUTTON_Pause                1093
#define IDC_BUTTON_Resume               1094
#define IDC_BUTTON_StepBack             1095
#define IDC_BUTTON_Forward              1096
#define IDC_EDIT_ControlPlay_DeviceID   1097
#define IDC_EDIT_Record_DevcieID        1099
#define IDC_EDIT_Record_s8FileName      1100
#define IDC_EDIT_Record_u32MaxSize      1101
#define IDC_EDIT_Record_u32MaxTime      1102
#define IDC_EDIT_Record_u8StopCode      1103
#define IDC_EDIT_Record_u16SRC_ChID1    1104
#define IDC_EDIT_Record_u16SRC_ChID2    1105
#define IDC_CHECK_s8MixEnable           1106
#define IDC_CHECK_s8IsAppend            1107
#define IDC_RADIO_MIXER_FROM_NULL       1108
#define IDC_RADIO_MIXER_FROM_INPUT      1109
#define IDC_RADIO_MIXER_FROM_PLAY       1110
#define IDC_RADIO_MIXER_FROM_CONF       1111
#define IDC_RADIO_MIXER_FROM_RTP        1112
#define IDC_RADIO_MIXER_FROM_NULL2      1113
#define IDC_EDIT_ControlRecord_DeviceID 1113
#define IDC_RADIO_MIXER_FROM_INPUT2     1114
#define IDC_EDIT_u32StepSize            1114
#define IDC_RADIO_MIXER_FROM_PLAY2      1115
#define IDC_EDIT_u32SpeedSize           1115
#define IDC_RADIO_MIXER_FROM_CONF2      1116
#define IDC_RADIO_MIXER_FROM_RTP2       1117
#define IDC_RADIO_InputOpt_0            1120
#define IDC_RADIO_InputOpt_1            1121
#define IDC_RADIO_InputOpt_2            1122
#define IDC_RADIO_OutputOpt_0           1123
#define IDC_RADIO_OutputOpt_1           1124
#define IDC_RADIO_OutputOpt_2           1125
#define IDC_EDIT_Conf_DeviceID          1126
#define IDC_EDIT_Media_DeviceID         1127
#define IDC_COMBO_ParamType             1127
#define IDC_EDIT_ParamVoice_DeviceID    1128
#define IDC_CHECK_In_u8AgcEnable        1129
#define IDC_EDIT_ParamCAS_DeviceID      1129
#define IDC_RADIO_In_ALS_Mode           1130
#define IDC_RADIO_In_AGC_Mode           1131
#define IDC_CHECK_In_u8EcEnable         1132
#define IDC_RADIO_In_Ref_Input          1133
#define IDC_RADIO_In_Ref_Output         1134
#define IDC_CHECK_In_u8VadEnable        1135
#define IDC_CHECK_In_u8TadEnable        1136
#define IDC_EDIT_In_u16FixGain          1137
#define IDC_EDIT_In_u16EcRefCh          1138
#define IDC_CHECK_Out_u8AgcEnable       1139
#define IDC_RADIO_Out_ALS_Mode          1140
#define IDC_RADIO_Out_AGC_Mode          1141
#define IDC_RADIO_Out_Silence           1142
#define IDC_RADIO_Out_Input             1143
#define IDC_RADIO_Out_Play              1144
#define IDC_RADIO_Out_Mixer             1147
#define IDC_EDIT_Out_u16FixGain         1148
#define IDC_CHECK_u8InputCtrlValid      1149
#define IDC_CHECK_u8OutputCtrlValid     1150
#define IDC_CHECK_u8GtdCtrlValid        1151
#define IDC_CHECK_u8PlayGainMode        1152
#define IDC_CHECK_Gtd_u8ChannelEnable   1153
#define IDC_CHECK_Gtd_u8DTMFEnable      1154
#define IDC_CHECK_Gtd_u8MR2FEnable      1155
#define IDC_CHECK_Gtd_u8MR2BEnable      1156
#define IDC_CHECK_Gtd_u8GTDEnable       1157
#define IDC_EDIT_Out_u16SRC_ChID1       1158
#define IDC_EDIT_Out_u16SRC_ChID2       1159
#define IDC_EDIT_Gtd_u8GTDID            1160
#define IDC_COMBO_IndexList             1161
#define IDC_EDIT_Play_u16FixGain        1161
#define IDC_EDIT_BuildPlayIndex         1162
#define IDC_COMBO_NowIndexList          1163
#define IDC_RADIO_INDEX_FILE            1165
#define IDC_EDIT_BuildIndex_DeviceID    1166
#define IDC_RADIO_INDEX_RAM             1167
#define IDC_BUTTON_Build                1168
#define IDC_EDIT_u16IoLen               1169
#define IDC_EDIT_DataContent            1170
#define IDC_EDIT_DevcieID               1171
#define IDC_BUTTON1                     1172
#define IDC_BUTTON2                     1173
#define IDC_COMBO1                      1178
#define IDC_CHECK_DEBUG                 1179
#define IDC_COMBO_SRCMODE               1179
#define IDC_COMBO_ENVELOP_2             1179
#define IDC_COMBO_ENVELOP_3             1180
#define IDC_EDIT_TRUNK_DEV              1181
#define IDC_COMBO_ENVELOP_4             1181
#define IDC_RADIO_CALLERID_DISABLE      1182
#define IDC_COMBO_ENVELOP_5             1182
#define IDC_RADIO_CALLERID_FSK          1183
#define IDC_RADIO_CALLERID_DTMF         1184
#define IDC_RADIO_CALLERID_FSKORDTMF    1185
#define IDC_RADIO_DIALTONE_DONTDETECT   1187
#define IDC_RADIO_DIALTONE_DETECT       1188
#define IDC_RADIO_CALLOUTMETHOD_APPFULL 1189
#define IDC_RADIO_CALLOUTMETHOD_RNGBACK 1190
#define IDC_RADIO_CALLOUTMETHOD_POLARITY 1191
#define IDC_EDIT_VOC_DEV                1192
#define IDC_EDIT_CALLIN_RNGCOUNT        1193
#define IDC_EDIT_CALLINRINGCOUNT        1193
#define IDC_RADIO_SINGLEPULSE           1199
#define IDC_RADIO_DOUBLEPULSE           1200
#define IDC_RADIO_TRIPPULSE             1201
#define IDC_EDIT_CALLOUT_RNG_TIMEOUT    1202
#define IDC_RADIO_DONT_SENDDIALTONE     1203
#define IDC_RADIO_AUTO_SENDDIALTONE1    1204
#define IDC_RADIO_AUTO_SENDDIALTONE2    1205
#define IDC_RADIO_APP_FULLCONTROL       1206
#define IDC_RADIO_AUTO_RECVCALLEE       1207
#define IDC_EDIT_CALLEE_LEN             1208
#define IDC_EDIT_INTERDIGITTIMEOUT      1209
#define IDC_EDIT_FULLDIALTIMEOUT        1210
#define IDC_EDIT_USER_DEV               1211
#define IDC_EDIT_DSPIP                  1212
#define IDC_BUTTON_CONN                 1213
#define IDC_EDIT_DSPPORT                1214
#define IDC_BUTTON_DISCONN              1215
#define IDC_COMBO_ENCODETYPE            1217
#define IDC_BUTTON_RECCSP               1220
#define IDC_BUTTON_CTRLRECCSP           1221
#define IDC_BUTTON_PLAYCSP              1222
#define IDC_EDIT_PACKLEN                1223
#define IDC_BUTTON_CTRLPLAYCSP          1223
#define IDC_EDIT_RECCSP_FILE            1224
#define IDC_BUTTON_CTXUNLINK            1225
#define IDC_BUTTON_CTXLINK              1226
#define IDC_EDIT_DATALEN                1227
#define IDC_EDIT_TASKID                 1228
#define IDC_COMBO_DATATYPE              1230
#define IDC_EDIT1                       1231
#define IDC_COMBO_FAXTYPE               1232
#define IDC_EDIT_FREQ1_INDEX            1232
#define IDC_EDIT_IPDEV                  1233
#define IDC_EDIT_FREQ2_INDEX            1233
#define IDC_EDIT_VOCDEV                 1234
#define IDC_EDIT_FREQ3_INDEX            1234
#define IDC_RADIO_MIXER_FROM_IP         1239
#define IDC_RADIO_OTHER                 1241
#define IDC_RADIO_IP                    1242
#define IDC_RADIO_VOIP                  1242
#define IDC_RADIO_H323                  1243
#define IDC_RADIO_SIP                   1244
#define IDC_EDIT_CALLEE_ADDR            1245
#define IDC_EDIT_CALLEE_PORT            1246
#define IDC_RADIO_SEND                  1249
#define IDC_RADIO_RECV                  1250
#define IDC_EDIT_rxDataTimeOut          1252
#define IDC_EDIT_txBit1Freq             1253
#define IDC_EDIT_txBit0Freq             1254
#define IDC_EDIT_tx55Count              1255
#define IDC_EDIT_txAllOneSamples        1256
#define IDC_EDIT_rxFilterWindow         1257
#define IDC_EDIT_rxPeriodTheshold       1258
#define IDC_EDIT_rxAllOneSamples        1259
#define IDC_EDIT_rx55Count              1260
#define IDC_EDIT_m_u8MinHookFlashTime   1261
#define IDC_EDIT_m_u8MaxHookFlashTime   1262
#define IDC_EDIT_GTDID_1                1263
#define IDC_EDIT_MINONTIME1_1           1264
#define IDC_EDIT_THRESHOLD_1            1265
#define IDC_EDIT_FREQ_MASK_1            1266
#define IDC_EDIT_GTDID_2                1267
#define IDC_EDIT_REPATCOUNT_1           1268
#define IDC_EDIT_MAXONTIME1_1           1269
#define IDC_EDIT_MINOFFTIME1_1          1270
#define IDC_EDIT_MAXOFFTIME1_1          1271
#define IDC_EDIT_MINONTIME2_1           1272
#define IDC_EDIT_MAXONTIME2_1           1273
#define IDC_EDIT_MINOFFTIME2_1          1274
#define IDC_EDIT21                      1275
#define IDC_EDIT_MINONTIME1_2           1276
#define IDC_EDIT_THRESHOLD_2            1277
#define IDC_EDIT_FREQ_MASK_2            1278
#define IDC_EDIT_REPATCOUNT_2           1279
#define IDC_EDIT_MAXONTIME1_2           1280
#define IDC_EDIT_MINOFFTIME1_2          1281
#define IDC_EDIT_MAXOFFTIME1_2          1282
#define IDC_EDIT_MINONTIME2_2           1283
#define IDC_EDIT_MAXONTIME2_2           1284
#define IDC_EDIT_MINOFFTIME2_2          1285
#define IDC_EDIT_MAXOFFTIME2_2          1286
#define IDC_EDIT_GTDID_3                1287
#define IDC_EDIT_MINONTIME1_3           1288
#define IDC_EDIT_THRESHOLD_3            1289
#define IDC_EDIT_FREQ_MASK_3            1290
#define IDC_EDIT_REPATCOUNT_3           1291
#define IDC_EDIT_MAXONTIME1_3           1292
#define IDC_EDIT_MINOFFTIME1_3          1293
#define IDC_EDIT_MAXOFFTIME1_3          1294
#define IDC_EDIT_MINONTIME2_3           1295
#define IDC_EDIT_MAXONTIME2_3           1296
#define IDC_EDIT_MINOFFTIME2_3          1297
#define IDC_EDIT_MAXOFFTIME2_3          1298
#define IDC_EDIT_GTDID_4                1299
#define IDC_EDIT_MINONTIME1_4           1300
#define IDC_EDIT_THRESHOLD_4            1301
#define IDC_EDIT_FREQ_MASK_4            1302
#define IDC_EDIT_REPATCOUNT_4           1303
#define IDC_EDIT_MAXONTIME1_4           1304
#define IDC_EDIT_MINOFFTIME1_4          1305
#define IDC_EDIT_MAXOFFTIME1_4          1306
#define IDC_EDIT_MINONTIME2_4           1307
#define IDC_EDIT_MAXONTIME2_4           1308
#define IDC_EDIT_MINOFFTIME2_4          1309
#define IDC_EDIT_MAXOFFTIME2_4          1310
#define IDC_EDIT_GTDID_5                1311
#define IDC_EDIT_MINONTIME1_5           1312
#define IDC_EDIT_THRESHOLD_5            1313
#define IDC_EDIT_FREQ_MASK_5            1314
#define IDC_EDIT_REPATCOUNT_5           1315
#define IDC_EDIT_MAXONTIME1_5           1316
#define IDC_EDIT_MINOFFTIME1_5          1317
#define IDC_EDIT_MAXOFFTIME1_5          1318
#define IDC_EDIT_MINONTIME2_5           1319
#define IDC_EDIT_MAXONTIME2_5           1320
#define IDC_EDIT_MINOFFTIME2_5          1321
#define IDC_EDIT_MAXOFFTIME2_5          1322
#define IDC_EDIT_FREQ0_INDEX            1323
#define IDC_EDIT_FREQ0_COEF             1324
#define IDC_EDIT_FREQ1_COEF             1325
#define IDC_COMBO_ENVELOP_1             1326
#define IDC_TAB_GTD_FREQ                1327
#define IDC_EDIT_FREQ_INDEX             1328
#define IDC_EDIT_FREQ_COEF              1329
#define IDC_TAB_GTD_TONE                1330
#define IDC_EDIT_GTDID                  1331
#define IDC_EDIT_FREQ_MASK              1332
#define IDC_EDIT_THRESHOLD              1333
#define IDC_COMBO_ENVELOP               1334
#define IDC_EDIT_REPEATCOUNT            1335
#define IDC_EDIT_MINONTIME1             1336
#define IDC_EDIT_MAXONTIME1             1337
#define IDC_EDIT_MINOFFTIME1            1338
#define IDC_EDIT_MAXOFFTIME1            1339
#define IDC_EDIT_MINONTIME2             1340
#define IDC_EDIT_MAXONTIME2             1341
#define IDC_EDIT_MINOFFTIME2            1342
#define IDC_EDIT_MAXOFFTIME2            1343
#define IDC_CHECK_AT_CHANNEL_ENABLED    1344
#define IDC_EDIT_AT_RXSTATE             1345
#define IDC_EDIT_AT_TYPE                1346
#define IDC_EDIT_AT_TXSTATE             1347
#define IDC_CHECK_3GFAXTONE             1350
#define IDC_EDIT_HEADERTO               1352
#define IDC_EDIT_WITHHEADER             1353
#define IDC_EDIT_HEADERUSER             1354
#define IDC_EDIT_HEADERFROM             1355
#define IDC_EDIT_ANSWERCALLINTIMEOUT    1356
#define IDC_BUTTON_SENDFSK              1357
#define IDC_CHECK_Gtd_u8DPDEnable       1359
#define IDC_CHECK_Gtd_u8PVDEnable       1360
#define IDC_RADIO_BARGE_IN              1362
#define IDC_RADIO_NO_BARGE_IN           1363
#define IDC_EDIT_CALLOUTRINGTIMETOU     1364

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1365
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
